/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import StartBtnScript from "./script/StartBtnScript"
import MenuScript from "./script/MenuScript"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1136;
    static height:number=640;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Menu.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/StartBtnScript.ts",StartBtnScript);
        reg("script/MenuScript.ts",MenuScript);
    }
}
GameConfig.init();